"""
Configuration package for constants and settings.
"""

from .constants import (
    PI, E, GOLDEN_RATIO,
    APP_NAME, VERSION, AUTHOR,
    DEFAULT_FIBONACCI_LENGTH, DEFAULT_PRIME_LIMIT, DEFAULT_RANDOM_RANGE,
    GREETING_TEMPLATE, WELCOME_MESSAGE, COMPLETION_MESSAGE,
    SEPARATOR, Colors, DEMO_CONFIG, SAMPLE_NAMES, SAMPLE_NUMBERS, SAMPLE_WORDS
)

__all__ = [
    'PI', 'E', 'GOLDEN_RATIO',
    'APP_NAME', 'VERSION', 'AUTHOR',
    'DEFAULT_FIBONACCI_LENGTH', 'DEFAULT_PRIME_LIMIT', 'DEFAULT_RANDOM_RANGE',
    'GREETING_TEMPLATE', 'WELCOME_MESSAGE', 'COMPLETION_MESSAGE',
    'SEPARATOR', 'Colors', 'DEMO_CONFIG', 'SAMPLE_NAMES', 'SAMPLE_NUMBERS', 'SAMPLE_WORDS'
]
